### ISSUE TITLE
SFApp::OnExecute() missing return statement

### ISSUE THREAD

**Issue by AlmasB** [AidanDelaney/StarshipFontana#3]
https://github.com/AidanDelaney/StarshipFontana/blob/master/src/SFApp.cpp#L57

Was it supposed to return some error code if errors occurred within the main loop?

**Comment by AidanDelaney** [comment]
Yes, it should return SF_ERROR_NONE (at least) which comes from SFCommon.h.

**Comment by aaunel** [comment]
PR #6 addresses this, but may not be an acceptable fix.
